In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [3]:
np_arr = np.array(data)
x_np = torch.from_numpy(np_arr)
x_np

tensor([[1, 2],
        [3, 4]])

In [5]:
x_ones = torch.ones_like(x_data)
print(f"ones tensor:\n {x_ones}")
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"random tensor:\n {x_rand}")

ones tensor:
 tensor([[1, 1],
        [1, 1]])
random tensor:
 tensor([[0.4244, 0.4385],
        [0.9937, 0.3419]])


In [6]:
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"rand tensor:\n {rand_tensor}")
print(f"ones tensor:\n {ones_tensor}")
print(f"zeros tensor:\n {zeros_tensor}")

rand tensor:
 tensor([[0.1750, 0.0610, 0.3811],
        [0.4548, 0.5294, 0.1368]])
ones tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
zeros tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
tensor = torch.rand(3, 4)
print(f"tensor shape: {tensor.shape}")
print(f"tensor datatype: {tensor.dtype}")
print(f"tensor is stored in: {tensor.device}")

tensor shape: torch.Size([3, 4])
tensor datatype: torch.float32
tensor is stored in: cpu


In [8]:
# if there is GPU available, move the tensor to it
if torch.cuda.is_available():
    tensor = tensor.to("cuda")
else:
    print("No GPU! tensor remains in CPU.")

No GPU! tensor remains in CPU.


In [10]:
tensor = torch.rand(3, 4)
print(f"random tensor:\n {tensor}")
print(f"first row:\n {tensor[0]}")
print(f"first column:\n {tensor[:, 0]}")
print(f"last column:\n {tensor[..., -1]}")
print("replace second column with zeros:")
tensor[:, 1] = 0
print(tensor)

random tensor:
 tensor([[0.4142, 0.7411, 0.0164, 0.0416],
        [0.7843, 0.7966, 0.2787, 0.1653],
        [0.6302, 0.6015, 0.5601, 0.6828]])
first row:
 tensor([0.4142, 0.7411, 0.0164, 0.0416])
first column:
 tensor([0.4142, 0.7843, 0.6302])
last column:
 tensor([0.0416, 0.1653, 0.6828])
replace second column with zeros:
tensor([[0.4142, 0.0000, 0.0164, 0.0416],
        [0.7843, 0.0000, 0.2787, 0.1653],
        [0.6302, 0.0000, 0.5601, 0.6828]])


In [12]:
# concatenate tensors
cat_tensor = torch.cat([tensor, tensor, tensor], dim=0)
print(cat_tensor)

tensor([[0.4142, 0.0000, 0.0164, 0.0416],
        [0.7843, 0.0000, 0.2787, 0.1653],
        [0.6302, 0.0000, 0.5601, 0.6828],
        [0.4142, 0.0000, 0.0164, 0.0416],
        [0.7843, 0.0000, 0.2787, 0.1653],
        [0.6302, 0.0000, 0.5601, 0.6828],
        [0.4142, 0.0000, 0.0164, 0.0416],
        [0.7843, 0.0000, 0.2787, 0.1653],
        [0.6302, 0.0000, 0.5601, 0.6828]])


In [15]:
# compute matrix multiplications: y1, y2 and y3 are the same
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)
print("matrix multiplication:")
print(f"y1:\n {y1}")
print(f"y2:\n {y2}")
print(f"y3:\n {y3}")

# element-wise matrix multiplication: z1, z2 and z3 are the same
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
print("element-wise multiplication:\n")
print(f"z1:\n{z1}")
print(f"z2:\n{z2}")
print(f"z3:\n{z3}")

matrix multiplication:
y1:
 tensor([[0.1735, 0.3363, 0.2986],
        [0.3363, 0.7201, 0.7632],
        [0.2986, 0.7632, 1.1771]])
y2:
 tensor([[0.1735, 0.3363, 0.2986],
        [0.3363, 0.7201, 0.7632],
        [0.2986, 0.7632, 1.1771]])
y3:
 tensor([[0.1735, 0.3363, 0.2986],
        [0.3363, 0.7201, 0.7632],
        [0.2986, 0.7632, 1.1771]])
element-wise multiplication:

z1:
tensor([[1.7153e-01, 0.0000e+00, 2.6779e-04, 1.7334e-03],
        [6.1516e-01, 0.0000e+00, 7.7648e-02, 2.7309e-02],
        [3.9711e-01, 0.0000e+00, 3.1376e-01, 4.6620e-01]])
z2:
tensor([[1.7153e-01, 0.0000e+00, 2.6779e-04, 1.7334e-03],
        [6.1516e-01, 0.0000e+00, 7.7648e-02, 2.7309e-02],
        [3.9711e-01, 0.0000e+00, 3.1376e-01, 4.6620e-01]])
z3:
tensor([[1.7153e-01, 0.0000e+00, 2.6779e-04, 1.7334e-03],
        [6.1516e-01, 0.0000e+00, 7.7648e-02, 2.7309e-02],
        [3.9711e-01, 0.0000e+00, 3.1376e-01, 4.6620e-01]])


In [17]:
# use `.item()` methos to convert a single element tensor (e.g. by aggregation) to python value
agg = tensor.sum()
print(f"element-wise sum:\n {agg}", type(agg))
agg_item = agg.item()
print(f"item:\n {agg_item}", type(agg_item))

element-wise sum:
 3.573484182357788 <class 'torch.Tensor'>
item:
 3.573484182357788 <class 'float'>


In [18]:
# in-place operations are denoted by subscript, _ suffix
print(f"tensor:\n {tensor}")
tensor.add_(1)
print(f"in-place tensor+1:\n {tensor}")

tensor:
 tensor([[0.4142, 0.0000, 0.0164, 0.0416],
        [0.7843, 0.0000, 0.2787, 0.1653],
        [0.6302, 0.0000, 0.5601, 0.6828]])
in-place tensor+1:
 tensor([[1.4142, 1.0000, 1.0164, 1.0416],
        [1.7843, 1.0000, 1.2787, 1.1653],
        [1.6302, 1.0000, 1.5601, 1.6828]])


In [19]:
# tensor on the cpu and numpy arrays can share their underlying memory locations,
# a change in one will be reflected in the other
t = torch.ones(5)
print(f"t:\n {t}")
n = t.numpy()
print(f"n:\n {n}")

t.add_(4)
print(f"t+4:\n {t}")
print(f"n:\n {n}")

t:
 tensor([1., 1., 1., 1., 1.])
n:
 [1. 1. 1. 1. 1.]
t+4:
 tensor([5., 5., 5., 5., 5.])
n:
 [5. 5. 5. 5. 5.]


In [22]:
np.add(n, 1, out=n)
print(f"t:\n {t}", t.dtype)
print(f"n:\n {n}", n.dtype)

t:
 tensor([8., 8., 8., 8., 8.]) torch.float32
n:
 [8. 8. 8. 8. 8.] float32
